<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Phalcon Basic - Simple CRUD</title>
        <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('img/favicon.ico')?>"/>-->
        
        <link rel="apple-touch-icon" sizes="76x76" href="<?php echo $this->url->get('img/apple-icon.png') ?>">
        <link rel="icon" type="image/png" sizes="96x96" href="<?php echo $this->url->get('img/favicon.png')?>">
        <!-- Bootstrap core CSS     -->
        <link href="<?php echo $this->url->get('css/bootstrap.min.css')?>" rel="stylesheet" />

        <!-- Animation library for notifications   -->
        <link href="<?php echo $this->url->get('css/animate.min.css')?>" rel="stylesheet"/>

        <!--  Paper Dashboard core CSS    -->
        <link href="<?php echo $this->url->get('css/paper-dashboard.css')?>" rel="stylesheet"/>


        <!--  CSS for Demo Purpose, don't include it in your project     -->
        <link href="<? echo $this->url->get('css/demo.css')?>" rel="stylesheet" />


        <!--  Fonts and icons     -->
        <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
        <link href='https://fonts.googleapis.com/css?family=Muli:400,300' rel='stylesheet' type='text/css'>
        <link href="<?php echo $this->url->get('css/themify-icons.css')?>" rel="stylesheet">
    </head>
    <body>
        <div class="wrapper">
            <div class="sidebar" data-background-color="white" data-active-color="danger">
            <?php include"looked/sidebar.phtml"; ?>
            </div>
            <div class="main-panel">
            <?php include"looked/navbar.phtml"; ?>
            <?php echo $this->getContent(); ?>
            <?php include"looked/footer.phtml"; ?>
            </div>
        </div>
        
        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) 
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
        <!-- Latest compiled and minified JavaScript 
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>-->
        <!--   Core JS Files   -->
    <script src="<?php echo $this->url->get('js/jquery-1.10.2.js')?>" type="text/javascript"></script>
	<script src="<?php echo $this->url->get('js/bootstrap.min.js')?>" type="text/javascript"></script>

	<!--  Checkbox, Radio & Switch Plugins -->
	<script src="<?php echo $this->url->get('js/bootstrap-checkbox-radio.js')?>"></script>

	<!--  Charts Plugin -->
	<script src="<?php echo $this->url->get('js/chartist.min.js')?>"></script>

    <!--  Notifications Plugin    -->
    <script src="<?php echo $this->url->get('js/bootstrap-notify.js')?>"></script>

    <!--  Google Maps Plugin    -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script>

    <!-- Paper Dashboard Core javascript and methods for Demo purpose -->
	<script src="<?php echo $this->url->get('js/paper-dashboard.js')?>"></script>

	<!-- Paper Dashboard DEMO methods, don't include it in your project! -->
	<script src="<?php echo $this->url->get('js/demo.js')?>"></script>

	<script type="text/javascript">
    	$(document).ready(function(){

        	demo.initChartist();

        	$.notify({
            	icon: 'ti-gift',
            	message: "Welcome to <b>Paper Dashboard</b> - a beautiful Bootstrap freebie for your next project."

            },{
                type: 'success',
                timer: 4000
            });

    	});
	</script>
    </body>
</html>
